[package]
name = "lockfile"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
fs2 = "0.4"

[dev-dependencies]
tempfile = "3"
